# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './playfair.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(521, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_create_key = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create_key.setGeometry(QtCore.QRect(110, 410, 75, 23))
        self.btn_create_key.setObjectName("btn_create_key")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(250, 410, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(400, 410, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plaintext = QtWidgets.QLabel(self.centralwidget)
        self.plaintext.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.plaintext.setObjectName("plaintext")
        self.key = QtWidgets.QLabel(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(20, 170, 47, 13))
        self.key.setObjectName("key")
        self.keydisplay = QtWidgets.QLabel(self.centralwidget)
        self.keydisplay.setGeometry(QtCore.QRect(20, 230, 71, 16))
        self.keydisplay.setObjectName("keydisplay")
        self.ciphertext = QtWidgets.QLabel(self.centralwidget)
        self.ciphertext.setGeometry(QtCore.QRect(20, 320, 71, 16))
        self.ciphertext.setObjectName("ciphertext")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(100, 80, 391, 71))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_key.setGeometry(QtCore.QRect(100, 170, 391, 41))
        self.txt_key.setObjectName("txt_key")
        self.txt_create_key = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_create_key.setGeometry(QtCore.QRect(100, 230, 391, 71))
        self.txt_create_key.setObjectName("txt_create_key")
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(100, 320, 391, 71))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 521, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_create_key.setText(_translate("MainWindow", "Create Key"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.label.setText(_translate("MainWindow", "PLAYFAIR CIPHER"))
        self.plaintext.setText(_translate("MainWindow", "Plain Text:"))
        self.key.setText(_translate("MainWindow", "Key:"))
        self.keydisplay.setText(_translate("MainWindow", "Key Display:"))
        self.ciphertext.setText(_translate("MainWindow", "Cipher Text:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
